### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by pollytur** [MainRo/deep-speaker#9]
* Python version: 3.7

### Description

Is it possible to take weights for deeps speaker from https://github.com/a-nagrani/VGGVox and load them into your code and run?  And even if no, how can I train your model and test it after? I've looked through the **deep-speaker/deep_speaker/train/** folder but I still can not get how to path dataset for training

Thanks in advance)

**Comment by MainRo** [comment]
For now, this repository contains only the preparation and - partial - training part of the model, not the inference. So you cannot use the VGGVox models. Moreover, it seems they have been generated with matlab and I use pytorch here.

You need [makinage](http://www.makinage.org) to train a model. I did not put instruction yet because both makinage and deep-speaker are under development. BTW I need to update some parts of deep-speaker so that it works with the latest version of makinage.

So to make it clear: Do not expect to use code from this repository for now.

**Comment by pollytur** [comment]
Ok. Thank you for your answer!
